backend:
  name: git-gateway
  branch: main # Change if using a different branch

media_folder: "images"
public_folder: "/images"

collections:
  - name: "drumkit"
    label: "Drum Kit Sounds"
    folder: "sounds"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sound File", name: "sound", widget: "file" }
